---
title: "R_intro"
author: "wintree, Ph.D."
format: html
---

## R 환경

모든 객체 삭제하고 base package 에서 정의된 값 확인

```{r}
# 글로벌 환경(Global Environment)의 모든 객체 삭제
rm(list = ls())
ls()
# 정의된 객체 확인
letters
LETTERS
month.abb
month.name
```

어디에서 나온 값일까?

```{r}
# List all attached packages and the global environment
search()
```

package:base 에서 정의된 객체 확인

```{r}
# base 패키지에서 정의된 객체들 리스트
# objects() 함수와 ls() 함수의 기능은 같다.
objects("package:base", pattern = "^letter|^month")
```

letters 재정의 및 특정 환경을 명시적으로 지정

```{r}
# 객체 letters 재정의
letters <- "new value"
letters
# base package에서 정의된 객체
base::letters
```

## R 패키지

패키지 설치(한번만 실행)

```{r}
install.packages("tidyverse")
```

사용 가능한 모든 패키지 리스트

```{r}
library()
```

패키지 로딩(사용 전에 항상)

```{r}
# 패키지 로딩
library(foreign)
require(foreign)
```

패키지 사용 중지

```{r}
# 패키지 사용 중지
detach("package:foreign", unload = TRUE)
```

데이터

```{r}
# datasets 패키지 데이터
data()
# 사용 가능한 모든 데이터 리스트
data(package = .packages(all.available = TRUE))
```

패키지의 데이터 보기

```{r}
# 로드된 패키지의 데이터는 데이터 이름 사용
cars
# 로드되지 않은 패키지의 데이터
data(fruit, package = "stringr")
fruit
ggplot2::mpg
```
